// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiApp.Models;

namespace DataTestLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiApp.Models.Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<bool>("Flag");

                    b.Property<string>("Name");

                    b.Property<Guid>("Prop1Id");

                    b.Property<Guid>("Prop2Id");

                    b.Property<decimal>("Sum");

                    b.HasKey("Id");

                    b.HasIndex("Prop1Id");

                    b.HasIndex("Prop2Id");

                    b.ToTable("Datas");
                });

            modelBuilder.Entity("WebApiApp.Models.Property1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Property1s");
                });

            modelBuilder.Entity("WebApiApp.Models.Property2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Property2s");
                });

            modelBuilder.Entity("WebApiApp.Models.SubData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DataId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("DataId");

                    b.ToTable("SubDatas");
                });

            modelBuilder.Entity("WebApiApp.Models.Data", b =>
                {
                    b.HasOne("WebApiApp.Models.Property1", "Prop1")
                        .WithMany()
                        .HasForeignKey("Prop1Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiApp.Models.Property2", "Prop2")
                        .WithMany()
                        .HasForeignKey("Prop2Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiApp.Models.SubData", b =>
                {
                    b.HasOne("WebApiApp.Models.Data", "Data")
                        .WithMany("SubData")
                        .HasForeignKey("DataId");
                });
#pragma warning restore 612, 618
        }
    }
}
